### ISSUE TITLE
Add/Remove Roles?

### ISSUE THREAD

**Issue by johnnyoshika** [bcjobs/infra#2]
@dmitrynogin, for adding and removing roles for a user, should we include it in Infra?

`Infra.Authentications.IUsers`
- AddToRoleAsync(string userId, string role)
- RemoveFromRoleAsync(string userId, string role)

`Infra.Authentications.Identity.Services.Users`

If you think this is correct, I can request @ma-gu to add it.

**Comment by dmitrynogin** [comment]
Yep, makes sense. We might also have 

```
    Task<IEnumerable<string>> GetRolesAsync(string userId)
```

**Comment by johnnyoshika** [comment]
Thank you @dmitrynogin.

@ma-gu: I re-assigned this issue to you.  It would be great if you can implement this when you have a chance.  Thank you!

**Comment by johnnyoshika** [comment]
Completed in https://github.com/bcjobs/infra/commit/8053b672ee1d44c1b1ed16a2af77852f2d4dd32e
